version: 2.1

orbs:
  python: circleci/python@2.1.1  # You can keep the orb for reusable commands

jobs:
  build-and-test:
    executor: win/default       # Use Windows VM executor
    steps:
      - checkout

      - run:
          name: Install Python
          command: |
            choco install python --version=3.12.0 -y
            refreshenv
            python --version

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run tests
          command: pytest

workflows:
  sample:
    jobs:
      - build-and-test
